package data;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;


public abstract class DataAccessObject implements DBConstants {

    protected int id;

    // General save method for all objects that extend DataAccessObject (like Frage)
    public void save() {
        String sql = getSqlString(); // Use the SQL string generated by the object

        try (Connection conn = DataManager.getInstance().getConnection(); 
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            // Set the parameters for the prepared statement dynamically
            setPreparedStatementParameters(stmt); 

            // Execute the SQL query
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("Object erfolgreich gespeichert!");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException("Error saving object", e);
        }
    }

    // Abstract method to get the SQL query string for the specific object (e.g., Frage)
    public abstract String getSqlString();

    // Abstract method to get the table name for the specific object
    public abstract String getTableName();

    // This method will set the parameters for the PreparedStatement dynamically
    protected abstract void setPreparedStatementParameters(PreparedStatement stmt) throws SQLException;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
}
